export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// These styles apply to every route in the application
import "./globals.css";

import "../firebaseConfig";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log("Main layout");

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
